# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Build static site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export SPATIAL_GAME_URL=http://$PROD_DOMAIN
            else
              export SPATIAL_GAME_URL=http://$STAGING_DOMAIN
            fi
            npm run build

      - deploy:
          name: Deploy to S3
          command: |
            sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
            curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
            sudo pip install -q awscli --upgrade
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export BUCKET=$PROD_DOMAIN
            else
              export BUCKET=$STAGING_DOMAIN
            fi
            aws s3 cp ~/repo/build s3://$BUCKET/ --recursive --acl public-read

